In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df_final_demo = pd.read_csv("./df_final_demo.txt")
d2_1 = pd.read_csv("./df_final_web_data_pt_1.txt")
d2_2 = pd.read_csv("./df_final_web_data_pt_2.txt")
df_experiment_clients = pd.read_csv("./df_final_experiment_clients.txt")

In [3]:
df_final_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [4]:
d2_1

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
343136,2443347,465784886_73090545671,136329900_10529659391_316129,confirm,2017-03-31 15:15:46
343137,2443347,465784886_73090545671,136329900_10529659391_316129,step_3,2017-03-31 15:14:53
343138,2443347,465784886_73090545671,136329900_10529659391_316129,step_2,2017-03-31 15:12:08
343139,2443347,465784886_73090545671,136329900_10529659391_316129,step_1,2017-03-31 15:11:37
343140,2443347,465784886_73090545671,136329900_10529659391_316129,start,2017-03-31 15:10:47

In [5]:
d2_2

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58
...,...,...,...,...,...
412259,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
412260,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
412261,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
412262,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
412263,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

In [6]:
df_experiment_clients

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
70604    2443347       NaN
70605    8788427       NaN
70606     266828       NaN
70607    1266421       NaN
70608    9895983       NaN

[70609 rows x 2 columns]

# Data Cleaning

Stack the rows on top of each other using pd.concat() and reset the index:

In [7]:
df_final_web_data = pd.concat([d2_1, d2_2], ignore_index=True)
df_final_web_data

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,step_1,2017-05-24 18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,start,2017-05-24 18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,start,2017-06-03 12:17:09

Merging d1 and d3 due to same row number, using client_id as unique identifier. d3 is the list revealing which clients were part of the grand experiment so we need to remove the ones which were not:

In [8]:
df_final_demo = df_final_demo.merge(df_experiment_clients, how='inner', on='client_id')

df_final_demo = df_final_demo.dropna(subset=['Variation'])

In [9]:
df_final_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,Test
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,Control
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,Test
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,Test
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,Control
...,...,...,...,...,...,...,...,...,...,...
50495,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0,Test
50496,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,Control
50497,5826160,20.0,249.0,56.5,F,2.0,44837.16,2.0,5.0,Test
50498,8739285,19.0,229.0,69.5,F,2.0,44994.24,1.0,4.0,Test
50499,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,Test

In [10]:
df_final_demo.isnull().sum()

client_id            0
clnt_tenure_yr      12
clnt_tenure_mnth    12
clnt_age            13
gendr               12
num_accts           12
bal                 12
calls_6_mnth        12
logons_6_mnth       12
Variation            0
dtype: int64

In [11]:
df_final_demo.isnull().sum() / len(df_final_demo) * 100 # checking how important are the null values

client_id           0.000000
clnt_tenure_yr      0.023762
clnt_tenure_mnth    0.023762
clnt_age            0.025743
gendr               0.023762
num_accts           0.023762
bal                 0.023762
calls_6_mnth        0.023762
logons_6_mnth       0.023762
Variation           0.000000
dtype: float64

In [12]:
df_final_demo.dropna(how='all').shape # no full Null rows

(50500, 10)

In [13]:
df_final_demo.duplicated().sum() # no duplicated rows

np.int64(0)

In [14]:
df_final_demo.dropna(subset=['clnt_tenure_yr', 'clnt_tenure_mnth', 'clnt_age', 'gendr', 'num_accts', 'bal', 'calls_6_mnth', 'logons_6_mnth'], inplace = True)

In [15]:
df_final_demo['gendr'] = df_final_demo['gendr'].replace('X', 'U')

In [16]:
# List of columns that represent whole numbers
int_cols = ['clnt_tenure_yr', 'clnt_tenure_mnth', 'num_accts', 'calls_6_mnth', 'logons_6_mnth']

# Convert them to nullable integer type
df_final_demo[int_cols] = df_final_demo[int_cols].astype('Int64')

In [17]:
df_final_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6,73,60.5,U,2,45105.30,6,9,Test
1,2304905,7,94,58.0,U,2,110860.30,6,9,Control
2,1439522,5,64,32.0,U,2,52467.79,6,9,Test
3,1562045,16,198,49.0,M,2,67454.65,3,6,Test
4,5126305,12,145,33.0,F,2,103671.75,0,3,Control
...,...,...,...,...,...,...,...,...,...,...
50495,1780858,21,262,68.5,M,3,372100.59,6,9,Test
50496,6967120,21,260,68.5,M,3,4279873.38,6,9,Control
50497,5826160,20,249,56.5,F,2,44837.16,2,5,Test
50498,8739285,19,229,69.5,F,2,44994.24,1,4,Test
50499,7468138,18,222,61.0,F,3,209278.15,0,3,Test

## Cleaning Final Web Data

In [18]:
df_final_web_data.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [19]:
df_final_web_data['process_step'].value_counts()

process_step
start      243945
step_1     163193
step_2     133062
step_3     112242
confirm    102963
Name: count, dtype: int64

Assigning number values to process_step and date_time:

In [20]:
step_mapping = {
    'start': 0,
    'step_1': 1,
    'step_2': 2,
    'step_3': 3,
    'confirm': 4
}

df_final_web_data['process_step'] = df_final_web_data['process_step'].map(step_mapping)

In [21]:
df_final_web_data['date_time'] = pd.to_datetime(df_final_web_data['date_time'])

# Extract year, month, day, and the full time (HH:MM:SS)
df_final_web_data['year'] = df_final_web_data['date_time'].dt.year
df_final_web_data['month'] = df_final_web_data['date_time'].dt.month
df_final_web_data['day'] = df_final_web_data['date_time'].dt.day
df_final_web_data['time'] = df_final_web_data['date_time'].dt.time

In [22]:
df_final_web_data

,client_id,visitor_id,visit_id,process_step,date_time,year,month,day,time
0,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:27:07,2017,4,17,15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:26:51,2017,4,17,15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:19:22,2017,4,17,15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:19:13,2017,4,17,15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:18:04,2017,4,17,15:18:04
...,...,...,...,...,...,...,...,...,...
755400,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:46:10,2017,5,24,18:46:10
755401,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:45:29,2017,5,24,18:45:29
755402,9668240,388766751_9038881013,922267647_3096648104_968866,1,2017-05-24 18:44:51,2017,5,24,18:44:51
755403,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:44:34,2017,5,24,18:44:34
755404,674799,947159805_81558194550,86152093_47511127657_716022,0,2017-06-03 12:17:09,2017,6,3,12:17:09

In [23]:
# Save DataFrames to a new CSV file
df_final_demo.to_csv("df_final_demo_clean.csv", index=False)

In [24]:
df_final_web_data.to_csv("df_final_web_data_clean.csv", index=False)

In [29]:
# Build a client-level analysis dataset
# One row = one cleaned Test or Control participant

assert df_final_demo["client_id"].is_unique

# Keep only web events from cleaned experiment participants
web_participants = df_final_web_data.loc[
    df_final_web_data["client_id"].isin(
        df_final_demo["client_id"]
    )
].copy()

# Convert timestamps only in this analysis copy
web_participants["date_time"] = pd.to_datetime(
    web_participants["date_time"],
    errors="coerce"
)

# Count unique visits and total recorded events per client
visit_event_metrics = (
    web_participants.groupby("client_id")
    .agg(
        number_of_visits=("visit_id", "nunique"),
        number_of_events=("client_id", "size")
    )
    .reset_index()
)

# Count unique visits that reached the confirmation step
completed_visits = (
    web_participants.loc[web_participants["process_step"] == 4]
    .dropna(subset=["visit_id"])
    .groupby("client_id")["visit_id"]
    .nunique()
    .rename("completed_visits")
    .reset_index()
)


# Calculate duration separately inside every visit
web_participants["date_time"] = pd.to_datetime(web_participants["date_time"])

visit_durations = (
    web_participants
    .dropna(subset=["visit_id", "date_time"])
    .groupby(["client_id", "visit_id"])
    .agg(
        visit_start=("date_time", "min"),
        visit_end=("date_time", "max")
    )
    .reset_index()
)

visit_durations["visit_duration_seconds"] = (
    visit_durations["visit_end"]
    - visit_durations["visit_start"]
).dt.total_seconds()

# Calculate the average visit duration for every client
average_duration = (
    visit_durations.groupby("client_id")
    .agg(
        average_visit_duration_seconds=(
            "visit_duration_seconds",
            "mean"
        )
    )
    .reset_index()
)


# Create the final client-level DataFrame

df_v1 = (
    df_final_demo
    .merge(
        visit_event_metrics,
        on="client_id",
        how="left",
        validate="one_to_one"
    )

    .merge(
        completed_visits,
        on="client_id",
        how="left",
        validate="one_to_one"
    )

    .merge(
        average_duration,
        on="client_id",
        how="left",
        validate="one_to_one"
    )
)

# Clients without web events receive zero counts
count_columns = [
    "number_of_visits",
    "number_of_events",
    "completed_visits"
]

df_v1[count_columns] = (
    df_v1[count_columns]
    .fillna(0)
    .astype(int)
)

# Keep duration as NaN when no valid timed visit exists
assert df_v1["client_id"].is_unique
assert len(df_v1) == len(df_final_demo)

display(df_v1.head())

display(
    df_v1[
        [
            "number_of_visits",
            "number_of_events",
            "completed_visits",
            "average_visit_duration_seconds"
        ]
    ].describe()
)

df_v1.to_csv("df_v1.csv", index=False)

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation,number_of_visits,number_of_events,completed_visits,average_visit_duration_seconds
0,836976,6,73,60.5,U,2,45105.30,6,9,Test,2,11,1,1017.0
1,2304905,7,94,58.0,U,2,110860.30,6,9,Control,1,6,1,295.0
2,1439522,5,64,32.0,U,2,52467.79,6,9,Test,2,5,0,58.5
3,1562045,16,198,49.0,M,2,67454.65,3,6,Test,1,1,0,0.0
4,5126305,12,145,33.0,F,2,103671.75,0,3,Control,1,1,0,0.0

,number_of_visits,number_of_events,completed_visits,average_visit_duration_seconds
count,50487.000000,50487.000000,50487.000000,50487.000000
mean,1.375106,6.361935,0.750015,312.240608
std,0.822863,4.200307,0.646480,486.910228
min,1.000000,1.000000,0.000000,0.000000
25%,1.000000,5.000000,0.000000,94.000000
50%,1.000000,5.000000,1.000000,190.500000
75%,2.000000,7.000000,1.000000,361.000000
max,18.000000,90.000000,11.000000,22895.000000